# Ansible requirements
roles:
- name: willshersystems.sshd
- name: geerlingguy.pip
- name: geerlingguy.docker
- name: geerlingguy.swap
- name: pallxk.code_server
- name: xanmanning.k3s

collections:
- name: amazon.aws
  version: 1.5.1