- hosts: local
  tasks:
    - import_role:
        name: cloud_sandbox_infra

    - name: add managed instance as hosts
      add_host:
        name: "{{ item }}.{{ cloud_sandbox_domain_name }}"
        groups:
          - sandbox_ec2_instances
      loop: "{{ cloud_sandbox_ec2_instances_names }}"
      loop_control:
        label: "{{ item }}.{{ cloud_sandbox_domain_name }}"
      changed_when: false
      tags: [ always ]

- hosts: sandbox_ec2_instances
  remote_user: "{{ cloud_sandbox_ec2_remote_user }}"
  gather_facts: "{{ cloud_sandbox_state == 'present' }}"
  vars:
    ansible_ssh_private_key_file: "{{ cloud_sandbox_ec2_ssh_key }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - role: cloud_sandbox_instance
      when: cloud_sandbox_state == 'present'
