- hosts: localhost
  vars:
    ansible_python_interpreter: /home/pbeucher/git/formations/cloud-sandbox-manager/.venv/bin/python
  tasks:
    - import_role:
        name: cloud_sandbox_infra
      vars:
        # Ensure infra is deleted
        cloud_sandbox_state: absent
