- hosts: local
  tasks:
    - import_role:
        name: cloud_sandbox_infra

    - name: add managed instance as hosts
      add_host:
        name: "{{ item }}.{{ cloud_sandbox_route53_dns_record_suffix }}"
        groups:
          - sandbox_ec2_instances
      loop: "{{ cloud_sandbox_ec2_instances_names }}"
      loop_control:
        label: "{{ item }}.{{ cloud_sandbox_route53_dns_record_suffix }}"

- hosts: sandbox_ec2_instances
  remote_user: "{{ cloud_sandbox_ec2_remote_user }}"
  vars:
    ansible_ssh_private_key_file: "{{ cloud_sandbox_ec2_ssh_key }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - cloud_sandbox_instance