download_url: https://galaxy.ansible.com/download/amazon-aws-1.5.1.tar.gz
format_version: 1.0.0
name: aws
namespace: amazon
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.5.1
version_url: https://galaxy.ansible.com/api/v2/collections/amazon/aws/versions/1.5.1/
