# Generate kubeconfig for EKS on all targets
- hosts: all
  remote_user: "{{ sandbox_user }}"
  
  tasks:
    - name: aws eks update-kubeconfig
      ansible.builtin.command: 
        cmd: aws eks update-kubeconfig --name cloud-sandbox-{{ sandbox_environment }}