# Generate kubeconfig for EKS on all targets
- hosts: all
  remote_user: root
  
  tasks:
    - name: aws eks update-kubeconfig
      become: true
      ansible.builtin.command: 
        cmd: aws eks update-kubeconfig --name cloud-sandbox-{{ sandbox_environment }}